// labview-ui/core/src/components/atoms/LVButton/LVButton.tsx
import React, { Component, PropsWithChildren } from "react";
import { colorMap, sizeMap } from "../../shared/styles";
import "../../index.css";
import { LoadingSpinner } from "../../shared/elements";
import {ATOM} from '../style'

export interface LVButtonProps extends LVBaseProps {
  loading?: boolean;
  hidden?: boolean;
  size?: "xsmall" | "small" | "medium" | "large" | "xlarge";
  onClick?: () => void;
}

const ButtonClasses: ATOM = {
  size: {
    xsmall: '',
    small: '',
    medium: '',
    large: '',
    xlarge: ''
  },
  variant: {
    default: '',
    secondary: '',
    outline: '',
    nav: '',
  },
}


/**
 * Primary UI component for user interaction
 */
export class LVButton extends Component<PropsWithChildren<LVButtonProps>> {
  private readonly base =
    "border-primary no-underline outline-primary-content uppercase font-bold text-center rounded hover:brightness-110 hover:scale-95 transition";

  private readonly loading = "pointer-events-none contrast-50";
  render() {
    return (
      <button
        className={[
          this.base,
          colorMap[this.props.color || "primary"],
          sizeMap[this.props.size || "medium"],
          this.props.hidden ? "hidden" : "",
          this.props.loading ? this.loading : "",
        ].join(" ")}
      >
        {this.props.loading ? (
          <LoadingSpinner
            className={
              this.props.color
                ? `fill-${this.props.color}-content `
                : "fill-primary-content"
            }
          />
        ) : null}
        {this.props.children}
      </button>
    );
  }
}

// labview-ui-lit/src/components/LVButton/LVButton.ts
import { LitElement, html } from "lit";
import { customElement, property } from "lit/decorators.js";
import { classCombiner, colorClasses, sizeClasses } from "../../shared/styles";
import install from "@twind/with-web-components";
import config from "../../twind.config";
const withTwind = install(config);

export interface ButtonProps {
  variant?: string;
  color?: "primary" | "secondary" | "accent";
  size?: "xsmall" | "small" | "medium" | "large";
  label?: string;
  onClick?: () => void;
}

@customElement("lv-btn")
export class LVButton extends withTwind(LitElement) {
  @property()
  color: string = "primary";

  @property()
  variant?: string = "default";

  @property()
  size: string = "medium";

  @property({ type: Boolean })
  hidden: boolean = false;

  @property()
  onClick?: () => void;

  private base =
    " rounded hover:scale-95 hover:brightness-110 uppercase font-semibold no-underline gap-2 border inline-flex flex-shrink-0 cursor-pointer select-none flex-wrap items-center justify-center border-transparent text-center transition duration-200 ease-out";

  override render() {
    const color = colorClasses[this.color];
    const size = sizeClasses[this.size];
    const classes = classCombiner(this.base, size, color);
    return html`<h1 .className=${classes}>
        <slot></slot>
      </h1>
      <p>|color: ${color} classes: ${classes}|</p> `;
  }
}
